version: '3'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "../prometheus.yml:/etc/prometheus/prometheus.yml"
    network_mode: host
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/provisioning/dashboard-conf.yml:/etc/grafana/provisioning/dashboards/conf.yml
      - ./grafana/provisioning/datasource-conf.yml:/etc/grafana/provisioning/datasources/conf.yml
      - ./grafana/provisioning/dashboards:/var/lib/grafana/dashboards
    network_mode: host
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    ports:
      - 3000:3000
    depends_on:
      - prometheus

