version: '3'
networks:
  localprom:
    driver: bridge
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "../prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - localprom
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    networks:
      - localprom
    ports:
      - 3000:3000
    depends_on:
      - prometheus

