global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
         - localhost:9090
  - job_name: simple_server
    static_configs:
      - targets:
         - ${GO_SERVER_IP}:9000
  - job_name: simple_server_node
    static_configs:
      - targets:
         - ${GO_SERVER_IP}:9100
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: "go-server"

